name    'ericsson-cacti'
version '0.1.0'
source 'git://github.com/Ericsson/puppet-module-cacti.git'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'Manages Cacti'
description 'Manages Cacti'
project_page 'https://github.com/Ericsson/puppet-module-cacti'

dependency 'puppetlabs/stdlib', '3.2.x'
dependency 'puppetlabs/apache', '>= 0.5.0'
